DELETE FROM WAREHOUSE ;
DELETE FROM DISTRICT ;
DELETE FROM ITEM ;
DELETE FROM CUSTOMER ;
DELETE FROM CUSTOMER_NAME ;
DELETE FROM HISTORY ;
DELETE FROM STOCK ;
DELETE FROM ORDERS ;
DELETE FROM NEW_ORDER ;
DELETE FROM ORDER_LINE ;
DELETE FROM LOADER_PERMIT;
DELETE FROM RUN_PERMIT;

exec @Resume;
